name: flat_and_fast
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg: ^0.22.0

  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_thunk: ^0.4.0
  redux_logging: ^0.5.0

  logger: ^1.1.0

  dio: ^4.0.1
  retrofit: ^2.0.1

  injectable: ^1.5.0
  get_it: ^7.2.0

  built_value:
  built_collection:
  flutter_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

  build_runner:
  built_value_generator:
  flutter_gen_runner:

  retrofit_generator: ^2.0.1
  injectable_generator: ^1.5.0

flutter_gen:
  line_length: 150

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/poketball_bottom_part.svg

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 600
